plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .idea
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

timezone: Europe/Kiev
markdown: kramdown
title: ''

url:  https://romasheva.cv
baseurl: ''

email: alla@romasheva.com

analytics: G-C6HYPQHN9F

author:
  name: Alla Romasheva
  twitter: AllaRomasheva

twitter:
  username: AllaRomasheva
  card: summary_large_image

facebook:
  publisher: 100024493295482
  chat: 100930458520274

defaults:
  - scope:
      path: ''
    values:
      lang: 'en'
      layout: 'default'
      alternate:
        en: '/en/'
        ru: '/ru/'
        uk: '/uk/'
      image:
        path: '/assets/images/cover.jpg'
        width: '1000'
        height: '600'
  - scope:
      path: 'ru'
    values:
      lang: 'ru'
  - scope:
      path: 'uk'
    values:
      lang: 'uk'
  - scope:
      path: 'en'
    values:
      lang: 'en'
