plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - .idea
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

timezone: Europe/Kiev
markdown: kramdown
title: ''

markdown_ext: markdown,md,liquid

url:  https://romasheva.cv
baseurl: ''

email: alla@romasheva.com

analytics: G-C6HYPQHN9F

author:
  name: Alla Romasheva
  twitter: AllaRomasheva

twitter:
  username: AllaRomasheva
  card: summary_large_image

facebook:
  publisher: 100024493295482
  chat: 100930458520274


social:
  name: Alla Romasheva (Алла Ромашева)
  links:
    - https://romasheva.com
    - https://romasheva.design
    - https://www.facebook.com/romasheva.design/
    - https://www.instagram.com/romasheva.design/
    - https://twitter.com/allaromasheva
    - https://www.linkedin.com/in/romasheva/
    - https://www.behance.net/romasheva
    - https://dribbble.com/romasheva
    - https://ua.linkedin.com/in/алла-ромашева-051390174
    - https://github.com/allaromasheva
    - https://www.pexels.com/@alla-romasheva-3820560/


contacts:
  twitter: https://twitter.com/AllaRomasheva
  instagram: https://www.instagram.com/romasheva.design/
  linkedin: https://www.linkedin.com/in/romasheva/
  telegram: https://t.me/romasheva
  skype: skype:live:37e58384221057fa?chat
  messenger: https://m.me/romasheva.design

defaults:
  - scope:
      path: ''
    values:
      lang: 'en'
      layout: 'default'
      alternate:
        en: '/en/'
        ru: '/ru/'
        uk: '/uk/'
      image:
        path: '/assets/images/cover.jpg'
        width: '1000'
        height: '600'
      seo:
        links:
          - https://romasheva.com
          - https://romasheva.cv
          - https://www.facebook.com/romasheva.design/
          - https://www.instagram.com/romasheva.design/
          - https://twitter.com/allaromasheva
          - https://www.linkedin.com/in/romasheva/
          - https://www.behance.net/romasheva
          - https://dribbble.com/romasheva
          - https://ua.linkedin.com/in/алла-ромашева-051390174
          - https://github.com/allaromasheva
          - https://www.pexels.com/@alla-romasheva-3820560/

  - scope:
      path: 'ru'
    values:
      lang: 'ru'
  - scope:
      path: 'uk'
    values:
      lang: 'uk'
  - scope:
      path: 'en'
    values:
      lang: 'en'
